#!/bin/bash
set -e

echo "Starting Python server..."

# pip install virtualenv
# python -m virtualenv venv
# source venv/bin/activate
pip install -r requirements.txt
OPENAI_API_KEY=$1 python3 app.py # run bash script/start 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
